### ISSUE TITLE
URLs are being built with HTTP instead of HTTPS

### ISSUE THREAD

**Issue by ranihorev** [Flimm/django-fullurl#2]
Hey,

My website is running as HTTPS (using Cloudflare), but when I'm creating a link using fullurl it's created as HTTP. 
Can I fix it somehow?

p.s.
Other than that, great app!

**Comment by Flimm** [comment]
I think you need to set `SECURE_SSL_PROXY_HEADER` to the correct value.

https://docs.djangoproject.com/en/stable/ref/settings/#secure-proxy-ssl-header

Have a look into it and let me know if that fixes it.

**Comment by ranihorev** [comment]
Thanks! 
I saw another solution (can't find the link) - set environment variable HTTPS = 'on' 
What do you think? 

By the way, the warnings on the links you attached are a bit alarming. If you have some inputs, I would appreciate it.

**Comment by Flimm** [comment]
I can't comment on the environment variable `HTTPS`, I don't think Django pays attention to that.
