### ISSUE TITLE
Provide utility functions to use outside of templates

### ISSUE THREAD

**Issue by lorinkoz** [Flimm/django-fullurl#5]
Could you provide the same tags as utility functions to use in views, serializers, etc.? I need to build the full media url of a thumbnail generated in a serializer via `easy_thumbnails`.`get_thumbnailer`.

**Comment by Flimm** [comment]
Is [`request.build_absolute_uri`](https://docs.djangoproject.com/en/stable/ref/request-response/#django.http.HttpRequest.build_absolute_uri) what you are looking for?

**Comment by lorinkoz** [comment]
No, not always the full url of images is in the same domain of the current request. It's more like smartly prepending the `MEDIA_URL`, like I assume you're doing for the templatetag.

**Comment by Flimm** [comment]
I am using `request.build_absolute_uri`. It works like this:

```python
>>> request.build_absolute_uri("/hello")
'http://example.com/hello'
>>> request.build_absolute_uri("https://en.wikipedia.org/wiki/Django_(web_framework)")
'https://en.wikipedia.org/wiki/Django_(web_framework)'
```
