### ISSUE TITLE
'Context' object has no attribute 'request'

### ISSUE THREAD

**Issue by ghost** [Flimm/django-fullurl#6]
I am getting the error report:
'Context' object has no attribute 'request'

but the context has the request object.

```
context | [{'True': True, 'False': False, 'None': None}, {'csrfmiddlewaretoken': 're7WBQNr1gg4ihr5suA2FVOpfFkRZyzOrjb4oFOTyg5oaJ89mf72s8nxhCdpY3gT', 'email': '555@leserever.com', 'username': 'sffsdlf', 'password1': '555@leserever.com', 'password2': '555@leserever.com', 'request': <WSGIRequest: POST '/en/streets/register/'>}]
-- | --
self | <fullurl.templatetags.fullurl.FullURLNode object at 0x7f6e0c2a1710>
url | '/en/accounts/password/reset/'
```

**Comment by Flimm** [comment]
That's odd. How are you printing out this debug information? Are you using the template tag `{% include %}` with the `only` option?

**Comment by ghost** [comment]
thanks. I was trying to use it with django-post_office but apparently post-office does not keep the request object.  
https://github.com/ui/django-post_office/issues/300

the problem lies in the other plugin
